<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html"%>

<html>

<body>

<h2>Database Exception</h2>

<p>An unexpected database error has occurred. Please report this
error to your database administrator. Thank you for your cooperation.</p>

<hr />

<h3>Here is the message generated by the thrown database exception:</h3>
<p><html:errors /></p>

</body>

</html>
